def main():
    f = open("result_repoort.b","wb")
    for i in range(3):
        print(f"Record of Student No {i+1}")
        print("--------------------------------------------------")
        rollno=int(input(f"write rollno of Student {i+1}: "))
        f.write(rollno.to_bytes(rollno, byteorder ='big', signed=True))
        name = input("write  name: ")
        f.write(name.encode())
        course = input("write course name: ")
        f.write(course.encode())
        sessional = int(input("sessional marks: "))
        f.write(sessional.to_bytes(sessional, byteorder ='big'))
        mid = int(input("write mid marks: "))
        f.write(mid.to_bytes(mid, byteorder ='big', signed=True))
        final = int(input("write final marks: "))
        f.write(final.to_bytes(final, byteorder ='big', signed=True))
    f.close()
main()
